---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: cve-secrets-py
spec:
  name: cve-secrets-py
  keysMap:
    db-pwdpy:
      path: secrets/data/openeuler/cve-manager
      key: db-pwdpy
    db-uri:
      path: secrets/data/openeuler/cve-manager
      key: db-uri
    cve-email-sendaddr:
      path: secrets/data/openeuler/cve-manager
      key: cve-email-sendaddr
    cve-email-password:
      path: secrets/data/openeuler/cve-manager
      key: cve-email-password
